M48
; DRILL file {KiCad (7.0.0-0)} date Tuesday, March 07, 2023 at 12:57:02 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-07T12:57:02-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X183.305Y-135.7
X183.305Y-141.48
T2
X181.25Y-124.6
X181.25Y-131.4
T0
M30
